language: go

go: 
  - "1.12"

env:
- GO111MODULE=on

script: 
  - go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

  # - go test ./... -timeout=60m -run nothing -bench=. -cpu=1,2,4 -benchtime=2s

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1

notifications:
  email: false