language: go

go: 
  - "1.12"

env:
- GO111MODULE=on

script: 
  - go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

after_success:
  - bash <(curl https://codecov.io/bash)

git:
  depth: 1

notifications:
  email: false